# Generated by Django 5.0.2 on 2024-03-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
