# Generated by Django 5.0.2 on 2024-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_name_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
