# Generated by Django 5.0.2 on 2024-03-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
    ]
