# Generated by Django 5.0.2 on 2024-05-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
